# Generated by Django 4.1.5 on 2023-01-05 17:17

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=django.contrib.postgres.fields.citext.CICharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=django.contrib.postgres.fields.citext.CICharField(default='', max_length=200),
        ),
    ]
