# Generated by Django 4.1.5 on 2023-01-06 11:33

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_track_genres_alter_track_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='buyed',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CICharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
