# Generated by Django 4.1.5 on 2023-01-06 20:35

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_buyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='time',
            field=django.contrib.postgres.fields.citext.CITextField(default='0.00'),
        ),
    ]
