# Generated by Django 4.1.5 on 2023-01-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_track_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='stripe_product_id',
        ),
    ]
