# Generated by Django 4.1.5 on 2023-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_track_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='time',
        ),
    ]
